# Generated by Django 5.2.17 on 2026-09-24 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_managers_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='currency',
            field=models.CharField(default='RWF', max_length=3),
        ),
        migrations.AlterField(
            model_name='salary',
            name='currency',
            field=models.CharField(default='RWF', max_length=3),
        ),
    ]
