# Generated by Django 5.2.17 on 2026-09-24 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_employee_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='date',
            field=models.DateField(),
        ),
        migrations.CreateModel(
            name='AccountProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('employee', 'Employee'), ('employer', 'Employer')], max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account_profile', to=settings.AUTH_USER_MODEL)),
                ('business', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owner_profile', to='api.business')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.business'),
        ),
        migrations.AddField(
            model_name='holiday',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.business'),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(fields=('business', 'email'), name='unique_business_employee_email'),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(condition=models.Q(('business__isnull', True)), fields=('email',), name='unique_legacy_employee_email'),
        ),
        migrations.AddConstraint(
            model_name='holiday',
            constraint=models.UniqueConstraint(fields=('business', 'date'), name='unique_business_holiday_date'),
        ),
        migrations.AddConstraint(
            model_name='holiday',
            constraint=models.UniqueConstraint(condition=models.Q(('business__isnull', True)), fields=('date',), name='unique_legacy_holiday_date'),
        ),
        migrations.AddConstraint(
            model_name='accountprofile',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('business__isnull', True), ('role', 'employee')), models.Q(('business__isnull', False), ('role', 'employer')), _connector='OR'), name='account_role_matches_business'),
        ),
    ]
