# Generated by Django 5.2.17 on 2026-09-25 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_business_alter_employee_email_alter_holiday_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountprofile',
            name='employee',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account', to='api.employee'),
        ),
        migrations.AddField(
            model_name='accountprofile',
            name='must_change_password',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
