# Generated by Django 5.2.17 on 2026-10-02 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_platformmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformmessage',
            name='channel',
            field=models.CharField(choices=[('message', 'Message'), ('email', 'Email')], default='message', max_length=10),
        ),
    ]
