# Generated by Django 5.2.17 on 2026-10-02 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_platformmessage_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='status',
            field=models.CharField(choices=[('pending', 'Awaiting verification'), ('active', 'Active'), ('suspended', 'Suspended')], db_index=True, default='active', max_length=10),
        ),
        migrations.AddField(
            model_name='business',
            name='status_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='invite_email_failed',
            field=models.BooleanField(default=False),
        ),
    ]
