# Generated by Django 5.2.17 on 2026-10-08 09:30

import api.models
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_user_email_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_name', models.CharField(max_length=200)),
                ('asset_tag', models.CharField(blank=True, max_length=100)),
                ('incident_type', models.CharField(choices=[('damaged', 'Damaged'), ('lost', 'Lost'), ('misused', 'Misused')], default='damaged', max_length=20)),
                ('incident_date', models.DateField()),
                ('description', models.TextField()),
                ('estimated_loss', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('currency', models.CharField(default='RWF', max_length=3)),
                ('evidence', models.FileField(blank=True, upload_to=api.models.evidence_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png', 'webp', 'doc', 'docx'])])),
                ('status', models.CharField(choices=[('reported', 'Reported'), ('under_review', 'Under review'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='reported', max_length=20)),
                ('investigation_findings', models.TextField(blank=True)),
                ('employee_response', models.TextField(blank=True)),
                ('resolution', models.TextField(blank=True)),
                ('recovery_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('recovery_authorization', models.TextField(blank=True)),
                ('reported_by', models.CharField(blank=True, max_length=200)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_incidents', to='api.employee')),
            ],
            options={
                'ordering': ['-incident_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PayrollCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_pay', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('advance_deductions', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('other_deductions', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('total_deductions', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('net_pay', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('calculated_by', models.CharField(blank=True, max_length=200)),
                ('payroll', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calculation', to='api.payroll')),
            ],
        ),
        migrations.CreateModel(
            name='PayrollPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advance_deduction_limit_percent', models.DecimalField(decimal_places=2, default=Decimal('33.33'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payroll_policy', to='api.business')),
            ],
        ),
        migrations.CreateModel(
            name='SalaryAdvance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('currency', models.CharField(default='RWF', max_length=3)),
                ('issue_date', models.DateField()),
                ('reason', models.TextField()),
                ('installment_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('first_repayment_month', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('disbursed_on', models.DateField(blank=True, null=True)),
                ('disbursement_method', models.CharField(blank=True, choices=[('bank_transfer', 'Bank transfer'), ('mobile_money', 'Mobile money'), ('cash', 'Cash')], max_length=20)),
                ('disbursement_reference', models.CharField(blank=True, max_length=120)),
                ('approved_by', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_advances', to='api.employee')),
            ],
            options={
                'ordering': ['-issue_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PayrollDeductionLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('advance', 'Salary advance repayment'), ('other', 'Other deductions')], max_length=20)),
                ('name', models.CharField(max_length=150)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('calculation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='api.payrollcalculation')),
                ('salary_advance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.salaryadvance')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AdvanceRepayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('repaid_on', models.DateField()),
                ('source', models.CharField(choices=[('payroll', 'Payroll deduction'), ('manual', 'Direct repayment')], max_length=10)),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('recorded_by', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payroll', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advance_repayments', to='api.payroll')),
                ('advance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayments', to='api.salaryadvance')),
            ],
            options={
                'ordering': ['repaid_on', 'id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('payroll__isnull', False)), fields=('advance', 'payroll'), name='one_advance_deduction_per_payroll')],
            },
        ),
    ]
