# Generated by Django 5.2.17 on 2026-10-08 10:09

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_payroll_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollcalculation',
            name='asset_deductions',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='payrolldeductionline',
            name='asset_incident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_deductions', to='api.assetincident'),
        ),
        migrations.AlterField(
            model_name='payrolldeductionline',
            name='kind',
            field=models.CharField(choices=[('advance', 'Salary advance repayment'), ('asset', 'Asset misuse recovery'), ('other', 'Other deductions')], max_length=20),
        ),
    ]
