# Generated by Django 5.2.17 on 2026-10-08 10:45

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_payroll_asset_recovery'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryAdvanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('currency', models.CharField(default='RWF', max_length=3)),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=10)),
                ('decision_notes', models.TextField(blank=True)),
                ('decided_by', models.CharField(blank=True, max_length=200)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('advance', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request', to='api.salaryadvance')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_advance_requests', to='api.employee')),
            ],
            options={
                'ordering': ['-requested_at', '-id'],
            },
        ),
    ]
