# Generated by Django 5.2.17 on 2026-10-08 15:08

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_attendance_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='monthly_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='contract',
            name='salary_currency',
            field=models.CharField(default='RWF', max_length=3),
        ),
        migrations.AddField(
            model_name='payroll',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payroll', to='api.contract'),
        ),
    ]
