# Generated by Django 5.2.17 on 2026-10-09 08:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_contract_salary'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('building', models.CharField(max_length=100)),
                ('floor', models.CharField(max_length=30)),
                ('door_identifier', models.CharField(max_length=100)),
                ('created_by', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='api.business')),
            ],
            options={
                'ordering': ['building', 'floor', 'name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RoomAccessAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=100)),
                ('building', models.CharField(blank=True, max_length=100)),
                ('floor', models.CharField(blank=True, max_length=30)),
                ('user_name', models.CharField(max_length=200)),
                ('user_email', models.EmailField(blank=True, max_length=254)),
                ('user_role', models.CharField(max_length=10)),
                ('access_method', models.CharField(choices=[('nfc', 'NFC'), ('bluetooth', 'Bluetooth')], max_length=10)),
                ('result', models.CharField(choices=[('granted', 'Granted'), ('denied', 'Denied')], max_length=10)),
                ('denial_reason', models.CharField(blank=True, choices=[('not_member', 'Not part of this business'), ('admin_no_policy', 'No door authorization policy for administrators'), ('inactive', 'Employee profile is inactive'), ('not_approved', 'Contract not approved yet'), ('password_change_required', 'Temporary password not replaced yet'), ('no_permission', 'No access granted to this room'), ('hardware_not_configured', 'Door hardware integration not configured'), ('proximity_failed', 'Proximity not verified')], max_length=30)),
                ('unlock_status', models.CharField(blank=True, choices=[('confirmed', 'Door confirmed it unlocked'), ('unconfirmed', 'Unlock sent, no confirmation from the door'), ('failed', 'Door controller did not respond')], max_length=12)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_access_attempts', to='api.business')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_access_attempts', to='api.employee')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_attempts', to='api.room')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_access_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='RoomAccessGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_by', models.CharField(blank=True, max_length=200)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_grants', to='api.employee')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grants', to='api.room')),
            ],
            options={
                'ordering': ['room__name', 'employee__last_name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RoomPermissionChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=100)),
                ('employee_name', models.CharField(max_length=201)),
                ('employee_email', models.EmailField(max_length=254)),
                ('change', models.CharField(choices=[('granted', 'Access granted'), ('revoked', 'Access revoked')], max_length=10)),
                ('changed_by', models.CharField(blank=True, max_length=200)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_permission_changes', to='api.business')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.employee')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.room')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.UniqueConstraint(fields=('business', 'door_identifier'), name='unique_business_door_identifier'),
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.UniqueConstraint(fields=('business', 'building', 'floor', 'name'), name='unique_business_room'),
        ),
        migrations.AddIndex(
            model_name='roomaccessattempt',
            index=models.Index(fields=['business', 'created_at'], name='api_roomacc_busines_25937e_idx'),
        ),
        migrations.AddConstraint(
            model_name='roomaccessgrant',
            constraint=models.UniqueConstraint(fields=('room', 'employee'), name='unique_room_access_grant'),
        ),
    ]
