# Generated by Django 5.2.17 on 2026-10-09 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_room_access_control'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomaccessattempt',
            name='access_method',
            field=models.CharField(choices=[('nfc', 'NFC'), ('bluetooth', 'Bluetooth'), ('door_code', 'Door code (simulator)')], max_length=10),
        ),
        migrations.CreateModel(
            name='SimulatedDoor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret', models.CharField(max_length=64)),
                ('started_by', models.CharField(blank=True, max_length=200)),
                ('started_at', models.DateTimeField()),
                ('last_seen_at', models.DateTimeField()),
                ('unlocked_until', models.DateTimeField(blank=True, null=True)),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='simulated_door', to='api.room')),
            ],
        ),
    ]
