# Generated by Django 5.2.17 on 2026-10-09 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_door_simulator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomaccessattempt',
            name='access_method',
            field=models.CharField(choices=[('nfc', 'NFC'), ('bluetooth', 'Bluetooth'), ('range', 'Phone in range (simulator)'), ('door_code', 'Door code (simulator)')], max_length=10),
        ),
        migrations.AlterField(
            model_name='roomaccessattempt',
            name='denial_reason',
            field=models.CharField(blank=True, choices=[('not_member', 'Not part of this business'), ('admin_no_policy', 'No door authorization policy for administrators'), ('inactive', 'Employee profile is inactive'), ('not_approved', 'Contract not approved yet'), ('password_change_required', 'Temporary password not replaced yet'), ('no_permission', 'No access granted to this room'), ('hardware_not_configured', 'Door hardware integration not configured'), ('proximity_failed', 'Proximity not verified'), ('too_far', 'Too far from the door')], max_length=30),
        ),
    ]
